/**
 * fetch-coords.js
 * Run once: node fetch-coords.js
 *
 * Fetches cities + polygons from tzevaadom.co.il, then:
 * 1. Adds missing centroid coordinates to city-coordinates.ts
 * 2. Generates src/app/city-polygons.ts mapping Hebrew city name → polygon points
 */

const https = require('https');
const fs = require('fs');
const path = require('path');

function get(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': 'Mozilla/5.0' } }, (res) => {
      let data = '';
      res.on('data', (c) => (data += c));
      res.on('end', () => resolve({ status: res.statusCode, body: data }));
    }).on('error', reject);
  });
}

async function fetchJson(url) {
  const { status, body } = await get(url);
  if (status !== 200) throw new Error(`HTTP ${status} from ${url}`);
  return JSON.parse(body);
}

function centroid(polygon) {
  const lat = polygon.reduce((s, p) => s + p[0], 0) / polygon.length;
  const lng = polygon.reduce((s, p) => s + p[1], 0) / polygon.length;
  return [parseFloat(lat.toFixed(4)), parseFloat(lng.toFixed(4))];
}

// Round polygon coords to 4 decimal places to reduce file size
function roundPolygon(polygon) {
  return polygon.map(([lat, lng]) => [
    parseFloat(lat.toFixed(4)),
    parseFloat(lng.toFixed(4)),
  ]);
}

const coordsFile = path.join(__dirname, 'src/app/city-coordinates.ts');
const coordsSource = fs.readFileSync(coordsFile, 'utf8');
const existingKeys = new Set(
  [...coordsSource.matchAll(/'([^']+)':\s*\[/g)].map((m) => m[1])
);
console.log(`Existing coordinate entries: ${existingKeys.size}`);

(async () => {
  console.log('Fetching cities list...');
  const citiesData = await fetchJson('https://www.tzevaadom.co.il/static/cities.json?v=9');

  console.log('Fetching polygons...');
  const polygons = await fetchJson('https://www.tzevaadom.co.il/static/polygons.json?v=4');

  const cities = citiesData.cities || citiesData;
  console.log(`Total cities from tzevaadom: ${Object.keys(cities).length}`);

  const missingCoords = [];
  const polygonEntries = [];
  const noPolygon = [];

  for (const [name, data] of Object.entries(cities)) {
    const heName = data.he || name;
    const polygon = polygons[String(data.id)];

    if (!polygon || polygon.length === 0) {
      noPolygon.push(heName);
      continue;
    }

    const rounded = roundPolygon(polygon);

    // Collect polygon entry for every city that has one
    polygonEntries.push({ name: heName, polygon: rounded });

    // Only add to coordinates if missing
    if (!existingKeys.has(heName)) {
      const [lat, lng] = centroid(polygon);
      missingCoords.push({ name: heName, lat, lng });
    }
  }

  // ── 1. Update city-coordinates.ts ────────────────────────────────────────
  if (missingCoords.length > 0) {
    const coordLines = missingCoords
      .map(({ name, lat, lng }) => `  '${name}': [${lat}, ${lng}],`)
      .join('\n');
    const updated = coordsSource.replace(/^};$/m, coordLines + '\n};');
    fs.writeFileSync(coordsFile, updated, 'utf8');
    console.log(`✅ Added ${missingCoords.length} new coordinate entries to city-coordinates.ts`);
  } else {
    console.log('Coordinates: nothing new to add.');
  }

  // ── 2. Generate city-polygons.ts ─────────────────────────────────────────
  const polygonLines = polygonEntries
    .map(({ name, polygon }) => {
      const escaped = name.replace(/'/g, "\\'");
      const pts = polygon.map(([lat, lng]) => `[${lat},${lng}]`).join(',');
      return `  '${escaped}':[${pts}]`;
    })
    .join(',\n');

  const polygonsTs =
    `// Auto-generated by fetch-coords.js — do not edit manually\n` +
    `export const CITY_POLYGONS: Record<string, [number, number][]> = {\n` +
    polygonLines + '\n};\n';

  const polygonsFile = path.join(__dirname, 'src/app/city-polygons.ts');
  fs.writeFileSync(polygonsFile, polygonsTs, 'utf8');
  console.log(`✅ Generated city-polygons.ts with ${polygonEntries.length} cities`);

  if (noPolygon.length > 0) {
    console.log(`⚠️  ${noPolygon.length} cities had no polygon data (skipped)`);
  }
})().catch((e) => {
  console.error('Failed:', e.message);
  process.exit(1);
});
